@s-01-usuarios.sql
@s-02-entidades.sql
@s-03-tablas-temporales.sql
@s-04-tablas-externas.sql
@s-05-secuencias.sql
@s-06-indices.sql
@s-07-sinonimos.sql
@s-08-vistas.sql
@s-09-carga-inicial.sql
@s-10-consultas.sql
@s-11-tr-valida_num_web.sql
@s-12-tr-valida_num_web-prueba.sql
@s-11-tr-valida_estado_vuelo.sql
@s-12-tr-valida_estado_vuelo-prueba.sql
@s-13-p-pase-abordar.sql
@s-14-p-pase-abordar-prueba.sql
@s-13-p-registra_maletas.sql
@s-14-p-registra_maletas-prueba.sql
@s-13-p-registrar_tripulacion.sql
@s-14-p-registrar_tripulacion-prueba.sql
@s-15-fx-calcula_paquetes.sql
@s-16-fx-calcula_paquetes_prueba.sql
@s-15-fx-num-asientos.sql
@s-16-fx-num-asientos-prueba.sql
@s-15-fx-total-sueldo.sql
@s-16-fx-total-sueldo-prueba.sql

disconnect
